sudo: required
sevices:
  - docker
before_install:
  - docker build -t reaz/react-docker -f Dockerfile.dev .
script:
  - docker run reaz/react-docker npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: "dreact"
  env: "Dreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-436977664913"
  bucket_path: "dreact"
  on:
    branch: master